### ISSUE TITLE
Using Vue.js solves a lot of this

### ISSUE THREAD

**Issue by zoomclub** [jareware/css-architecture#5]
Thanks for this article in a time when I'm dusting off my CSS again. As I'm reading I can see that Vue (my recent framework choice) solves much of the points you raise. For instance, the Vue single file components work like the shadow DOM out of the box. Here are some relevant Vue links, I'd be interested in your take on Vue's approach.

http://rc.vuejs.org/guide/single-file-components.html
http://rc.vuejs.org/guide/class-and-style.html

**Comment by jareware** [comment]
Hey @zoomclub, thanks for your feedback!

I've been following the Web Components spec [for a long time](https://twitter.com/search?q=%40jareware%20shadow%20dom&src=typd), and I'm tremendously pleased with [recent developments](https://twitter.com/jareware/status/787579225666617344) in that scene.

That said, I'm not yet fully convinced Shadow DOM is ready for prime time, even with (or perhaps specifically because) all the polyfills in place. For a limited audience with a known set of recent browsers? Definitely! For the general population with whatever browser they have? Maybe in a few years.

FWIW, I do mention Shadow DOM several times in the article, as the gold standard in web isolation.
